# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/jsequeira/Proyectos/Karat/Karat_FPGA_Viv/Kat_FPGA.cache/wt [current_project]
set_property parent.project_path C:/Users/jsequeira/Proyectos/Karat/Karat_FPGA_Viv/Kat_FPGA.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/jsequeira/Proyectos/Karat/source/rtl/multiplier_combinational.v
  C:/Users/jsequeira/Proyectos/Karat/source/rtl/adder.v
  C:/Users/jsequeira/Proyectos/Karat/source/rtl/substractor.v
  C:/Users/jsequeira/Proyectos/Karat/source/rtl/KOA_FPGA.v
  C:/Users/jsequeira/Proyectos/Karat/source/rtl/KOA_c_v3.v
  C:/Users/jsequeira/Proyectos/Karat/source/rtl/RegisterAdd.v
  C:/Users/jsequeira/Proyectos/Karat/source/rtl/RecursiveKOA.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/jsequeira/Proyectos/Karat/Karat_FPGA_Viv/Nexys4_Master.xdc
set_property used_in_implementation false [get_files C:/Users/jsequeira/Proyectos/Karat/Karat_FPGA_Viv/Nexys4_Master.xdc]


synth_design -top RecursiveKOA -part xc7a100tcsg324-1 -directive AreaOptimized_high -control_set_opt_threshold 1


write_checkpoint -force -noxdef RecursiveKOA.dcp

catch { report_utilization -file RecursiveKOA_utilization_synth.rpt -pb RecursiveKOA_utilization_synth.pb }
