set_property SRC_FILE_INFO {cfile:C:/Users/jsequeira/Documents/Floating-Point-Unit-master/NATURAL_LOGARITHM_RTL/Nexys4_Master.xdc rfile:../../../../../../../Documents/Floating-Point-Unit-master/NATURAL_LOGARITHM_RTL/Nexys4_Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E3 [get_ports clk]
set_property src_info {type:XDC file:1 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E16 [get_ports rst]
