# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/jsequeira/Proyectos/Add_Sub/Add_Sub_FPGA_Viv/.Xil/Vivado-9052-RDS1/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a100tcsg324-1

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog {
      C:/Users/jsequeira/Proyectos/Karat/source/rtl/Multiplexer_AC.v
      C:/Users/jsequeira/Proyectos/Karat/source/rtl/Greater_Comparator.v
      C:/Users/jsequeira/Proyectos/Karat/source/rtl/Comparator_Less.v
      C:/Users/jsequeira/Proyectos/Karat/source/rtl/RegisterAdd.v
      C:/Users/jsequeira/Proyectos/Karat/source/rtl/shift_mux.v
      C:/Users/jsequeira/Proyectos/Karat/source/rtl/Rotate_Mux_Array.v
      C:/Users/jsequeira/Proyectos/Karat/source/rtl/xor_tri.v
      C:/Users/jsequeira/Proyectos/Karat/source/rtl/sgn_result.v
      C:/Users/jsequeira/Proyectos/Karat/source/rtl/Priority_Codec_64.v
      C:/Users/jsequeira/Proyectos/Karat/source/rtl/Priority_Codec_32.v
      C:/Users/jsequeira/Proyectos/Karat/source/rtl/Mux_3x1.v
      C:/Users/jsequeira/Proyectos/Karat/source/rtl/MultiplexTxT.v
      C:/Users/jsequeira/Proyectos/Karat/source/rtl/Comparators.v
      C:/Users/jsequeira/Proyectos/Karat/source/rtl/Comparator.v
      C:/Users/jsequeira/Proyectos/Karat/source/rtl/add_sub_carry_out.v
      C:/Users/jsequeira/Proyectos/Karat/source/rtl/Mux_Array.v
      C:/Users/jsequeira/Proyectos/Karat/source/rtl/Tenth_Phase.v
      C:/Users/jsequeira/Proyectos/Karat/source/rtl/Round_Sgf_Dec.v
      C:/Users/jsequeira/Proyectos/Karat/source/rtl/Oper_Start_In.v
      C:/Users/jsequeira/Proyectos/Karat/source/rtl/LZD.v
      C:/Users/jsequeira/Proyectos/Karat/source/rtl/FSM_Add_Subtract.v
      C:/Users/jsequeira/Proyectos/Karat/source/rtl/exp_operation.v
      C:/Users/jsequeira/Proyectos/Karat/source/rtl/Add_Subt.v
      C:/Users/jsequeira/Proyectos/Karat/source/rtl/Barrel_shifter.v
      C:/Users/jsequeira/Proyectos/Karat/source/rtl/FPU_Add_Subtract_Function.v
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top FPU_Add_Subtract_Function
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "C:/Users/jsequeira/Proyectos/Add_Sub/Add_Sub_FPGA_Viv/.Xil/Vivado-9052-RDS1/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
      rt::run_rtlelab -module $rt::top
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }

    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
