set_property SRC_FILE_INFO {cfile:/home/jorge/Documents/Proyecto_Lopez/project_1/project_1.srcs/constrs_1/imports/RTL/Nexys4_Master.xdc rfile:../../../../../project_1.srcs/constrs_1/imports/RTL/Nexys4_Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property src_info {type:XDC file:1 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property src_info {type:XDC file:1 line:724 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name clk -waveform {0.000 5.000} [get_ports clk]
set_property src_info {type:XDC file:1 line:725 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks clk] -min -add_delay 2.000 [get_ports rst]
set_property src_info {type:XDC file:1 line:726 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks clk] -max -add_delay 4.000 [get_ports rst]
