# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/jorge/Karatsuba_FPU/Karatsuba.cache/wt [current_project]
set_property parent.project_path /home/jorge/Karatsuba_FPU/Karatsuba.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  /home/jorge/Karatsuba_FPU/Karatsuba.srcs/sources_1/old/Multiplexer_AC.v
  /home/jorge/Karatsuba_FPU/Karatsuba.srcs/sources_1/old/substractor.v
  /home/jorge/Karatsuba_FPU/Karatsuba.srcs/sources_1/old/RegisterMult.v
  /home/jorge/Karatsuba_FPU/Karatsuba.srcs/sources_1/old/OR_Module.v
  /home/jorge/Karatsuba_FPU/Karatsuba.srcs/sources_1/old/multiplier.v
  /home/jorge/Karatsuba_FPU/Karatsuba.srcs/sources_1/old/Deco_Round_Mult.v
  /home/jorge/Karatsuba_FPU/Karatsuba.srcs/sources_1/old/Comparator_Equal.v
  /home/jorge/Karatsuba_FPU/Karatsuba.srcs/sources_1/old/adder.v
  /home/jorge/Karatsuba_FPU/Karatsuba.srcs/sources_1/old/shift_mux.v
  /home/jorge/Karatsuba_FPU/Karatsuba.srcs/sources_1/old/Comparator_Less.v
  /home/jorge/Karatsuba_FPU/Karatsuba.srcs/sources_1/old/RegisterAdd.v
  /home/jorge/Karatsuba_FPU/Karatsuba.srcs/sources_1/old/Mux_3x1.v
  /home/jorge/Karatsuba_FPU/Karatsuba.srcs/sources_1/old/add_sub_carry_out.v
  /home/jorge/Karatsuba_FPU/Karatsuba.srcs/sources_1/old/Zero_InfMult_Unit.v
  /home/jorge/Karatsuba_FPU/Karatsuba.srcs/sources_1/old/XOR_M.v
  /home/jorge/Karatsuba_FPU/Karatsuba.srcs/sources_1/old/Sgf_Multiplication.v
  /home/jorge/Karatsuba_FPU/Karatsuba.srcs/sources_1/old/Round_decoder_M.v
  /home/jorge/Karatsuba_FPU/Karatsuba.srcs/sources_1/old/FSM_Mult_Function.v
  /home/jorge/Karatsuba_FPU/Karatsuba.srcs/sources_1/old/First_Phase_M.v
  /home/jorge/Karatsuba_FPU/Karatsuba.srcs/sources_1/old/Exp_operation_m.v
  /home/jorge/Karatsuba_FPU/Karatsuba.srcs/sources_1/old/Barrel_Shifter_M.v
  /home/jorge/Karatsuba_FPU/Karatsuba.srcs/sources_1/old/Adder_Round.v
  /home/jorge/Karatsuba_FPU/Karatsuba.srcs/sources_1/old/Tenth_Phase.v
  /home/jorge/Karatsuba_FPU/Karatsuba.srcs/sources_1/old/FPU_Multiplication_Function.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top FPU_Multiplication_Function -part xc7a100tcsg324-1


write_checkpoint -force -noxdef FPU_Multiplication_Function.dcp

catch { report_utilization -file FPU_Multiplication_Function_utilization_synth.rpt -pb FPU_Multiplication_Function_utilization_synth.pb }
