# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/jsequeira/Karatsuba/Karatsuba.cache/wt [current_project]
set_property parent.project_path C:/Users/jsequeira/Karatsuba/Karatsuba.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/jsequeira/Documents/Floating-Point-Unit-master/FPU_Add_subt_Mult/RTL/Mult/substractor.v
  C:/Users/jsequeira/Documents/Floating-Point-Unit-master/FPU_Add_subt_Mult/RTL/Mult/adder.v
  C:/Users/jsequeira/Karatsuba/Karatsuba.srcs/sources_1/new/multiplier_combinational.v
  C:/Users/jsequeira/Documents/Floating-Point-Unit-master/FPU_Add_subt_Mult/RTL/Add-Subt/RegisterAdd.v
  C:/Users/jsequeira/Karatsuba/Karatsuba.srcs/sources_1/new/KOA.v
  C:/Users/jsequeira/Karatsuba/Karatsuba.srcs/sources_1/new/KOA_2.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top KOA_2 -part xc7a100tcsg324-1


write_checkpoint -force -noxdef KOA_2.dcp

catch { report_utilization -file KOA_2_utilization_synth.rpt -pb KOA_2_utilization_synth.pb }
