# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/jsequeira/Proyectos/Cordic/CORDIC_FPGA_dryruns/CORDIC_FPGA_dryruns.cache/wt [current_project]
set_property parent.project_path C:/Users/jsequeira/Proyectos/Cordic/CORDIC_FPGA_dryruns/CORDIC_FPGA_dryruns.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/jsequeira/Proyectos/project_1.xpr/project_1/project_1.srcs/sim_1/imports/Proyecto_De_Graduacion/FPU_FLM/RTL/Add-Subt/Multiplexer_AC.v
  C:/Users/jsequeira/Proyectos/project_1.xpr/project_1/project_1.srcs/sim_1/imports/Proyecto_De_Graduacion/FPU_FLM/RTL/Mult/Comparator_Less.v
  C:/Users/jsequeira/Proyectos/project_1.xpr/project_1/project_1.srcs/sim_1/imports/Proyecto_De_Graduacion/FPU_FLM/RTL/Add-Subt/shift_mux.v
  C:/Users/jsequeira/Proyectos/project_1.xpr/project_1/project_1.srcs/sim_1/imports/Proyecto_De_Graduacion/FPU_FLM/RTL/Add-Subt/Rotate_Mux_Array.v
  C:/Users/jsequeira/Proyectos/project_1.xpr/project_1/project_1.srcs/sim_1/imports/Proyecto_De_Graduacion/FPU_FLM/RTL/Add-Subt/RegisterAdd.v
  C:/Users/jsequeira/Proyectos/project_1.xpr/project_1/project_1.srcs/sim_1/imports/Add-Subt/Greater_Comparator.v
  C:/Users/jsequeira/Proyectos/project_1.xpr/project_1/project_1.srcs/sim_1/imports/Proyecto_De_Graduacion/FPU_FLM/RTL/Add-Subt/xor_tri.v
  C:/Users/jsequeira/Proyectos/project_1.xpr/project_1/project_1.srcs/sim_1/imports/Proyecto_De_Graduacion/FPU_FLM/RTL/Add-Subt/sgn_result.v
  C:/Users/jsequeira/Proyectos/project_1.xpr/project_1/project_1.srcs/sim_1/imports/Proyecto_De_Graduacion/FPU_FLM/RTL/Add-Subt/Priority_Codec_64.v
  C:/Users/jsequeira/Proyectos/project_1.xpr/project_1/project_1.srcs/sim_1/imports/Proyecto_De_Graduacion/FPU_FLM/RTL/Add-Subt/Priority_Codec_32.v
  C:/Users/jsequeira/Proyectos/project_1.xpr/project_1/project_1.srcs/sim_1/imports/Proyecto_De_Graduacion/FPU_FLM/RTL/Add-Subt/Mux_Array.v
  C:/Users/jsequeira/Proyectos/project_1.xpr/project_1/project_1.srcs/sim_1/imports/Proyecto_De_Graduacion/FPU_FLM/RTL/Add-Subt/Mux_3x1.v
  C:/Users/jsequeira/Proyectos/project_1.xpr/project_1/project_1.srcs/sim_1/imports/Proyecto_De_Graduacion/FPU_FLM/RTL/Add-Subt/MultiplexTxT.v
  C:/Users/jsequeira/Proyectos/project_1.xpr/project_1/project_1.srcs/sim_1/imports/Proyecto_De_Graduacion/FPU_FLM/RTL/Add-Subt/Comparator.v
  C:/Users/jsequeira/Proyectos/project_1.xpr/project_1/project_1.srcs/sim_1/imports/Proyecto_De_Graduacion/FPU_FLM/RTL/Add-Subt/add_sub_carry_out.v
  C:/Users/jsequeira/Proyectos/project_1.xpr/project_1/project_1.srcs/sim_1/imports/Add-Subt/Comparators.v
  C:/Users/jsequeira/Proyectos/project_1.xpr/project_1/project_1.srcs/sim_1/imports/Proyecto_De_Graduacion/FPU_FLM/RTL/Add-Subt/Tenth_Phase.v
  C:/Users/jsequeira/Proyectos/project_1.xpr/project_1/project_1.srcs/sim_1/imports/Proyecto_De_Graduacion/FPU_FLM/RTL/Add-Subt/Round_Sgf_Dec.v
  C:/Users/jsequeira/Proyectos/project_1.xpr/project_1/project_1.srcs/sim_1/imports/Proyecto_De_Graduacion/FPU_FLM/RTL/Add-Subt/Oper_Start_In.v
  C:/Users/jsequeira/Proyectos/project_1.xpr/project_1/project_1.srcs/sim_1/imports/Proyecto_De_Graduacion/FPU_FLM/RTL/Add-Subt/LZD.v
  C:/Users/jsequeira/Proyectos/project_1.xpr/project_1/project_1.srcs/sim_1/imports/Proyecto_De_Graduacion/FPU_FLM/RTL/Add-Subt/FSM_Add_Subtract.v
  C:/Users/jsequeira/Proyectos/project_1.xpr/project_1/project_1.srcs/sim_1/imports/Proyecto_De_Graduacion/FPU_FLM/RTL/Add-Subt/exp_operation.v
  C:/Users/jsequeira/Proyectos/project_1.xpr/project_1/project_1.srcs/sim_1/imports/Proyecto_De_Graduacion/FPU_FLM/RTL/Add-Subt/Barrel_shifter.v
  C:/Users/jsequeira/Proyectos/project_1.xpr/project_1/project_1.srcs/sim_1/imports/Proyecto_De_Graduacion/FPU_FLM/RTL/Add-Subt/Add_Subt.v
  C:/Users/jsequeira/Documents/Floating-Point-Unit-master/Coprocesador_CORDIC_RTL/sine_cosine_CORDIC/Simple_Subt.v
  C:/Users/jsequeira/Documents/Floating-Point-Unit-master/Coprocesador_CORDIC_RTL/sine_cosine_CORDIC/sign_inverter.v
  C:/Users/jsequeira/Documents/Floating-Point-Unit-master/Coprocesador_CORDIC_RTL/sine_cosine_CORDIC/Op_Select.v
  C:/Users/jsequeira/Documents/Floating-Point-Unit-master/Coprocesador_CORDIC_RTL/sine_cosine_CORDIC/Mux_3x1_b.v
  C:/Users/jsequeira/Documents/Floating-Point-Unit-master/Coprocesador_CORDIC_RTL/sine_cosine_CORDIC/Mux_2x1.v
  C:/Users/jsequeira/Documents/Floating-Point-Unit-master/Coprocesador_CORDIC_RTL/sine_cosine_CORDIC/LUT_ROM_64bits.v
  C:/Users/jsequeira/Documents/Floating-Point-Unit-master/Coprocesador_CORDIC_RTL/sine_cosine_CORDIC/LUT_ROM_32bits.v
  C:/Users/jsequeira/Documents/Floating-Point-Unit-master/Coprocesador_CORDIC_RTL/sine_cosine_CORDIC/d_ff_en.v
  C:/Users/jsequeira/Documents/Floating-Point-Unit-master/Coprocesador_CORDIC_RTL/sine_cosine_CORDIC/counter_up.v
  C:/Users/jsequeira/Documents/Floating-Point-Unit-master/Coprocesador_CORDIC_RTL/sine_cosine_CORDIC/counter_d.v
  C:/Users/jsequeira/Documents/Floating-Point-Unit-master/Coprocesador_CORDIC_RTL/sine_cosine_CORDIC/CORDIC_FSM_v2.v
  C:/Users/jsequeira/Proyectos/project_1.xpr/project_1/project_1.srcs/sim_1/imports/Proyecto_De_Graduacion/FPU_FLM/RTL/Add-Subt/FPU_Add_Subtract_Function.v
  C:/Users/jsequeira/Documents/Floating-Point-Unit-master/Coprocesador_CORDIC_RTL/sine_cosine_CORDIC/CORDIC_Arch2.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top CORDIC_Arch2 -part xc7a100tcsg324-1


write_checkpoint -force -noxdef CORDIC_Arch2.dcp

catch { report_utilization -file CORDIC_Arch2_utilization_synth.rpt -pb CORDIC_Arch2_utilization_synth.pb }
