# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/jsequeira/Proyectos/Karat/Karat_FPGA_Viv/Kat_FPGA.cache/wt [current_project]
set_property parent.project_path C:/Users/jsequeira/Proyectos/Karat/Karat_FPGA_Viv/Kat_FPGA.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/jsequeira/Proyectos/Karat/source/rtl/multiplier_combinational.v
  C:/Users/jsequeira/Proyectos/Karat/source/rtl/Multiplexer_AC.v
  C:/Users/jsequeira/Proyectos/Karat/source/rtl/adder.v
  C:/Users/jsequeira/Proyectos/Karat/source/rtl/substractor.v
  C:/Users/jsequeira/Proyectos/Karat/source/rtl/KOA_FPGA.v
  C:/Users/jsequeira/Proyectos/Karat/source/rtl/KOA_c_v3.v
  C:/Users/jsequeira/Proyectos/Karat/source/rtl/shift_mux.v
  C:/Users/jsequeira/Proyectos/Karat/source/rtl/RegisterMult.v
  C:/Users/jsequeira/Proyectos/Karat/source/rtl/OR_Module.v
  C:/Users/jsequeira/Proyectos/Karat/source/rtl/Mux_3x1.v
  C:/Users/jsequeira/Proyectos/Karat/source/rtl/Deco_Round_Mult.v
  C:/Users/jsequeira/Proyectos/Karat/source/rtl/Comparator_Less.v
  C:/Users/jsequeira/Proyectos/Karat/source/rtl/Comparator_Equal.v
  C:/Users/jsequeira/Proyectos/Karat/source/rtl/add_sub_carry_out.v
  C:/Users/jsequeira/Proyectos/Karat/source/rtl/RegisterAdd.v
  C:/Users/jsequeira/Proyectos/Karat/source/rtl/RecursiveKOA.v
  C:/Users/jsequeira/Proyectos/Karat/source/rtl/Zero_InfMult_Unit.v
  C:/Users/jsequeira/Proyectos/Karat/source/rtl/XOR_M.v
  C:/Users/jsequeira/Proyectos/Karat/source/rtl/Tenth_Phase.v
  C:/Users/jsequeira/Proyectos/Karat/source/rtl/Round_decoder_M.v
  C:/Users/jsequeira/Proyectos/Karat/source/rtl/FSM_Mult_Function.v
  C:/Users/jsequeira/Proyectos/Karat/source/rtl/First_Phase_M.v
  C:/Users/jsequeira/Proyectos/Karat/source/rtl/Exp_operation_m.v
  C:/Users/jsequeira/Proyectos/Karat/source/rtl/Barrel_Shifter_M.v
  C:/Users/jsequeira/Proyectos/Karat/source/rtl/Adder_Round.v
  C:/Users/jsequeira/Proyectos/Karat/source/rtl/FPU_Multiplication_Function_v2.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/jsequeira/Proyectos/Karat/Karat_FPGA_Viv/Nexys4_Master.xdc
set_property used_in_implementation false [get_files C:/Users/jsequeira/Proyectos/Karat/Karat_FPGA_Viv/Nexys4_Master.xdc]


synth_design -top FPU_Multiplication_Function_v2 -part xc7a100tcsg324-1


write_checkpoint -force -noxdef FPU_Multiplication_Function_v2.dcp

catch { report_utilization -file FPU_Multiplication_Function_v2_utilization_synth.rpt -pb FPU_Multiplication_Function_v2_utilization_synth.pb }
